name: build

on:
  push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: installing dependencies
      run: |
        sudo apt update
        sudo apt install -y autoconf automake libtool libsdl2-dev
    - name: configure
      run: |
        ./autogen.sh
        ./configure --disable-dependency-tracking
    - name: build
      run: |
        make
        make check
        make test
